/* eslint-disable import/prefer-default-export */
export const possitions = [
  {
    id: '1',
    title: 'Frontend',
    longTitle: 'Senior React.js Developer, Wealth Man-Agement Platform',
    description: `We are looking for a developer who rocks node and
         react, loves working in a fast-paced team environment and expects 
         the best from his or her peers.`,
    specialty: 'Frontend',
    level: 'Senior',
    weOffer: [
      '-Casual outfit and convenient working schedule',
      '-21 days of paid vacation and sick leave',
      '-Official employment',
      '-Competitive salary',
      '-Corporate English classes',
      '-INTO-SANA medical insurance for you and your family after 1 year of employment',
      '-Friendly team who are passionate about what they do',
      '-Commuting compensation for non-locals',
      '-2 months trial period',
    ],
    responsibilities: [
      '-Develop new product',
      '-Exiting porject involing new technologies',
      '-Professional development opportunities',
      '-Driving work on architecture design',
    ],
    requirements: [
      '-Have knowledge of JavaScript (React, ExtJS)',
      '-Have good experience with HTML5, CSS3, HTTP protocol',
      '-Have experience with implementing adaptive and responsive layout',
      '-Have more than 1 year of Frontnd development experience',
      '-Have basic knowledge of PHP, Node.js',
      '-Have good reading English, conversational would be a plus',
    ],
    date: '21.09.2017',

  },
  {
    id: '2',
    title: 'Back End',
    longTitle: 'Senior Back End Developer',
    description: `We are looking for an experienced and responsible engineer
         to be a part of our expert team working on an international HR product.`,
    specialty: 'Back End',
    level: 'Senior',
    weOffer: [
      '-Casual outfit and convenient working schedule',
      '-21 days of paid vacation and sick leave',
      '-Official employment',
      '-Competitive salary',
      '-Corporate English classes',
      '-INTO-SANA medical insurance for you and your family after 1 year of employment',
      '-Friendly team who are passionate about what they do',
      '-Commuting compensation for non-locals',
      '-2 months trial period',
    ],
    responsibilities: [
      '-Develop new product',
      '-Exiting porject involing new technologies',
      '-Professional development opportunities',
      '-Driving work on architecture design',
    ],
    requirements: [
      '-Have knowledge of JavaScript (React, ExtJS)',
      '-Have good experience with HTML5, CSS3, HTTP protocol',
      '-Have experience with implementing adaptive and responsive layout',
      '-Have more than 1 year of Frontnd development experience',
      '-Have basic knowledge of PHP, Node.js',
      '-Have good reading English, conversational would be a plus',
    ],
    date: '24.09.2017',
  },
  {
    id: '3',
    title: 'Frontend',
    longTitle: 'Middle JavaScript (React.js) Engineer',
    description: `SmartyAds is searching for Node.js Developer to join our
         fast-growing team and results-driven business. We are a programmatic`,
    specialty: 'Frontend',
    level: 'Middle',
    weOffer: [
      '-Casual outfit and convenient working schedule',
      '-21 days of paid vacation and sick leave',
      '-Official employment',
      '-Competitive salary',
      '-Corporate English classes',
      '-INTO-SANA medical insurance for you and your family after 1 year of employment',
      '-Friendly team who are passionate about what they do',
      '-Commuting compensation for non-locals',
      '-2 months trial period',
    ],
    responsibilities: [
      '-Develop new product',
      '-Exiting porject involing new technologies',
      '-Professional development opportunities',
      '-Driving work on architecture design',
    ],
    requirements: [
      '-Have knowledge of JavaScript (React, ExtJS)',
      '-Have good experience with HTML5, CSS3, HTTP protocol',
      '-Have experience with implementing adaptive and responsive layout',
      '-Have more than 1 year of Frontnd development experience',
      '-Have basic knowledge of PHP, Node.js',
      '-Have good reading English, conversational would be a plus',
    ],
    date: '4.10.2017',
  },
  {
    id: '4',
    title: 'Frontend',
    longTitle: 'Senior Angular.js Engineer',
    description: `DataArt has been engaged in software development and IT consulting
         since 1997. Companies that create interesting products and services have complex 
         business processes.`,
    specialty: 'Frontend',
    level: 'Senior',
    weOffer: [
      '-Casual outfit and convenient working schedule',
      '-21 days of paid vacation and sick leave',
      '-Official employment',
      '-Competitive salary',
      '-Corporate English classes',
      '-INTO-SANA medical insurance for you and your family after 1 year of employment',
      '-Friendly team who are passionate about what they do',
      '-Commuting compensation for non-locals',
      '-2 months trial period',
    ],
    responsibilities: [
      '-Develop new product',
      '-Exiting porject involing new technologies',
      '-Professional development opportunities',
      '-Driving work on architecture design',
    ],
    requirements: [
      '-Have knowledge of JavaScript (React, ExtJS)',
      '-Have good experience with HTML5, CSS3, HTTP protocol',
      '-Have experience with implementing adaptive and responsive layout',
      '-Have more than 1 year of Frontnd development experience',
      '-Have basic knowledge of PHP, Node.js',
      '-Have good reading English, conversational would be a plus',
    ],
    date: '7.10.2017',
  },
];
