
export const GET_VACANCIES_REQUEST = 'GET_VACANCIES_REQUEST';
export const GET_VACANCIES_SUCCESS = 'GET_VACANCIES_SUCCESS';
export const GET_VACANCIES_FAIL = 'GET_VACANCIES_FAIL';

export const EDIT_VACANCY_REQUEST = 'EDIT_VACANCY_REQUES';
export const EDIT_VACANCY_SUCCESS = 'EDIT_VACANCY_SUCCESS';
export const EDIT_VACANCY_FAIL = 'EDIT_VACANCY_FAIL';

export const ADD_VACANCY_REQUEST = 'ADD_VACANCY_REQUEST';
export const ADD_VACANCY_SUCCESS = 'ADD_VACANCY_SUCCESS';
export const ADD_VACANCY_FAIL = 'ADD_VACANCY_FAIL';

export const DELETE_VACANCY_REQUEST = 'DELETE_VACANCY_REQUEST';
export const DELETE_VACANCY__SUCCESS = 'DELETE_VACANCY__SUCCESS';
export const DELETE_VACANCY__FAIL = 'DELETE_VACANCY__FAIL';

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL';

export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUES';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAIL = 'EDIT_EVENT_FAIL';

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL';

export const ADD_EVENT_GALLERY_REQUEST = 'ADD_EVENT_GALLERY_REQUEST';
export const ADD_EVENT_GALLERY_SUCCESS = 'ADD_EVENT_GALLERY_SUCCESS';
export const ADD_EVENT_GALLERY_FAIL = 'ADD_EVENT_GALLERY_FAIL';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

export const DELETE_EVENT_PHOTOS_REQUEST = 'DELETE_EVENT_PHOTOS_REQUEST';
export const DELETE_EVENT_PHOTOS_SUCCESS = 'DELETE_EVENT_PHOTOS_SUCCESS';
export const DELETE_EVENT_PHOTOS_FAIL = 'DELETE_EVENT_PHOTOS_FAIL';

export const COMFIRM_ADDING_MODAL = 'COMFIRM_ADDING_MODAL';
export const CONFIRM_ADDING_EVENT_MODAL = 'COMFIRM_ADDING_EVENT_MODAL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_FAIL_VALIDATION = 'LOGIN_FAIL_VALIDATION';

export const CHANGE_LANG = 'CHANGE_LANG';
